version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
     #  - "nuget" #  create label in GitHub before adding it to pull requests
    assignees:
      - "jvizuetazivra"      
    open-pull-requests-limit: 11
